crypto: mark Num3072() noexcept to fix MuHash3072 default ctor
Fixes cross-compile build error on i686/mingw with newer GCC:
  error: use of deleted function 'MuHash3072::MuHash3072()'
  note: implicitly deleted because its exception-specification
        does not match the implicit exception-specification ''

MuHash3072() is declared 'noexcept = default', but its Num3072 members
had a non-noexcept default constructor, making the implicit MuHash3072
default ctor's noexcept spec mismatch and thus deleted.

Matches upstream Bitcoin Core practice.