test: include deque
boost 1.81.0 requires deque to be included directly:

  x86_64-pc-linux-gnu-g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config   -I. -I./obj -I/usr/include/db5.3/ -pthread -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include  -I./test/ -DBOOST_TEST_DYN_LINK  -I/usr/include/db5.3 -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS    -march=native -O2 -pipe -fomit-frame-pointer -c -o test/test_dogecoin-cuckoocache_tests.o `test -f 'test/cuckoocache_tests.cpp' || echo './'`test/cuckoocache_tests.cpp
test/cuckoocache_tests.cpp: In function ‘void cuckoocache_tests::test_cache_generations()’:
test/cuckoocache_tests.cpp:359:10: error: ‘deque’ is not a member of ‘std’
    359 |     std::deque<block_activity> last_few;
        |          ^~~~~
  test/cuckoocache_tests.cpp:9:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
      8 | #include <thread>
    +++ |+#include <deque>
      9 | #include <boost/thread.hpp>
  test/cuckoocache_tests.cpp:359:30: error: expected primary-expression before ‘>’ token
    359 |     std::deque<block_activity> last_few;
        |                              ^
  test/cuckoocache_tests.cpp:359:32: error: ‘last_few’ was not declared in this scope
    359 |     std::deque<block_activity> last_few;
        |                                ^~~~~~~~
  make[2]: *** [Makefile:9046: test/test_dogecoin-cuckoocache_tests.o] Error 1